### PR TITLE
Updates for automated build environment setup

### PR DESCRIPTION
**Pull request by historicbruno**
Latest version of MSYS2 and other dependencies for `get-be.ps1` script

### CODE REVIEW

**Comment by historicbruno** [comment]
I tried to maintain compatibility with Win 7, 8, 10 WDKs/SDKs, PowerShell 2.0 (default on Win7), and used VS 2017 Community on Win10 as my build system.

I'm actually testing with the Win10 WDK+SDK, but I've separated out the Win10-specific parts for separate pull requests. If desired, I could test against older WDKs, but it seems the trend of recent commits is moving to Windows 10 (I may be wrong).

**Comment by marmarek** [comment]
Windows 7 target as well as build environment should remain supported, at least until
 a) Windows 7 EOL
 b) gui-agent supports Windows 10 (it's mostly about qvideo driver)
whichever comes first.
After cursory review, it looks fine, good work! I'll also test it, but for that I need yet another clean windows install (it takes time).

**Comment by marmarek** [comment]
I'm trying this on Windows 7, and on two separate installations all the downloads done by `get-be.ps1` / `prepare-be.ps1` fails with `Failed to download ...: The underlying connection was closed: An unexpected error occurred on a send.`. Have you seen this problem?
I think it isn't related to any of those changes, as it happens also with `prepare-be.ps1` from master branch. Downloading the very same url with wget or a browser in that VM works. Looking at `tcpdump`, connection is made, but it's closed after few packets exchanges (I don't see what exactly, as it is TLS, and I don't have wireshark handy).

**Comment by historicbruno** [comment]
I wonder if it's trying to use a TLS version not supported by the server? Perhaps we can force it to use TLS 1.1 or higher (apparently .NET 3.5 doesn't support TLS 1.2). Might also be a problem with a not fully updated Windows 7?

But no, I haven't seen that on my build system. It's running Win 10 / .NET 4.6 though.

**Comment by historicbruno** [comment]
For example, running this command

     [Net.ServicePointManager]::SecurityProtocol 

on my fully updated Windows 7 SP1 HVM reveals only: Ssl3, Tls (1.0), and indeed HTTPS downloads using `System.Net.WebClient` fail with the same error.

`$PSVersionTable` shows it has CLRVersion 2.0.50727.8806, PSVersion 2.0.

**Comment by marmarek** [comment]
Ok, so that's it. Any simple way to make it work on Windows 7? Manually update powershell before?

**Comment by historicbruno** [comment]
I think that's the best way. Of course, that also means the scripts can be simplified slightly to use newer APIs (Extract-Archive, Get-Hash).

**Comment by marmarek** [comment]
I've updated powershell to 3.0 (`$PSVersionTable` confirms this), but it still fails, with `Could not create SSL/TLS secure channel`. `[Net.ServicePointManager]::SecurityProtocol` lists `Ssl3, Tls`.
It is necessary to also set `[Net.ServicePointManager]::SecurityProtocol` to `[Net.SecurityProtocolType]::Tls11, [Net.SecurityProtocolType]::Tls12`. At least on Windows 7. Could you add it to the script? Preferably with some future-proof method (to not downgrade settings newer version is already set).

**Comment by marmarek** [comment]
`get-be.ps1` fails with `CommandNotFoundException`  on:
 - `$gpg` call in line 296 (according to the message, `$gpg` is set to `C:\Users\user\Documents\qubes-builder\cache\windows-prereqs\gpg\pub\gpg.exe`, qubes-builder path looks correct)
 - `git` call in line 302 and 303

It is just after `[*] Importing Qubes OS signing keys...`.
This is after cloning qubes-builder, so git should be already somewhere there... Maybe it's because msys2 is moved just after that?

Also, it may be better idea to first download gpg4win and only then clone qubes-builder, so it's signature can be verified immediately after download. Specifically, before moving or using any files from within.

**Comment by historicbruno** [comment]
> At least on Windows 7. Could you add it to the script? Preferably with some future-proof method (to not downgrade settings newer version is already set).

Sure thing!  I have a clean Win 7 build env set up now. Fixing this is a little tricky but [this article](https://support.microsoft.com/en-us/help/3154518/support-for-tls-system-default-versions-included-in-the-net-framework) explains it all in detail. Updating PS isn't necessary if the user has a fully updated Win 7 system, we can take advantage of a hotfix that adds extension methods for TLS 1.2.

> `get-be.ps1` fails with `CommandNotFoundException` ...
> This is after cloning qubes-builder, so git should be already somewhere there... Maybe it's because msys2 is moved just after that?

Good catch, I completely forgot about testing that case.

> Also, it may be better idea to first download gpg4win and only then clone qubes-builder, so it's signature can be verified immediately after download. Specifically, before moving or using any files from within.

Agreed, I'll make these changes.

**Comment by historicbruno** [comment]
Hopefully latest commits take care of those issues. It keeps PS 2.0 compatibility, so that's not a problem anymore.
One possible future issue is that [makecert.exe is deprecated](https://docs.microsoft.com/en-us/windows/desktop/SecCrypto/makecert), and MS recommends using the PS commandlet [`New-SelfSignedCertificate`](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate) from the pkiclient module. I didn't use that in these commits, for two reasons:
1. Until Windows 10, the new commandlet has very limited features, mostly it's only good for copying an existing certificate.
2. It only supports PS 3.0 or newer.

There is an open source predecessor called [`New-SelfSignedCertificateEx`](https://gallery.technet.microsoft.com/scriptcenter/Self-signed-certificate-5920a7c6) which is similar to the latest  `New-SelfSignedCertificate` and also requires PS 3.0.

Here's some code to test how this could work (as opposed to scanning for the deprecated makecert.exe tool in Windows SDKs):
```powershell
Write-Host "[*] Generating code-signing certificate..."
$name = "Qubes Test Cert"
$subject = "CN=$name"
$cerPath = Join-Path $builderDir "qwt.cer"
$pfxPath = Join-Path $builderDir "qwt.pfx"
$emptyPass = (New-Object Security.SecureString)
if ([Environment]::OSVersion.Version.Major -ge 10)
{
    $cert = New-SelfSignedCertificate -Type CodeSigningCert -Subject $subject -KeyUsage DigitalSignature -CertStoreLocation "cert:\CurrentUser\My"
    Export-Certificate -Cert $cert -FilePath $cerPath
    Export-PfxCertificate -Cert $cert -FilePath $pfxPath -Password $emptyPass
}
else
{
    # open source predecessor to New-SelfSignedCertificate, requires PS 3.0+
    $pkgName = "New-SelfSignedCertificateEx"
    $url = "https://gallery.technet.microsoft.com/scriptcenter/Self-signed-certificate-5920a7c6/file/101251/2/New-SelfSignedCertificateEx.zip"
    $file = DownloadFile $url
    UnpackZip $file $tmpdir
    $scriptPath = Join-Path $tmpdir New-SelfSignedCertificateEx.ps1
    $result = Get-AuthenticodeSignature -FilePath $scriptPath
    if (($result.status -eq "Valid") -and ($result.SignerCertificate.Thumbprint -eq "1A8EAB5B0611AC0548F16A1675B8A3915CC2045E") -and ($result.SignerCertificate.Subject -eq "CN=Sysadmins LV IK, O=Sysadmins LV IK, L=Riga, C=LV"))
    {
        Import-Module $scriptPath
        $cert = New-SelfSignedCertificateEx -Exportable -Subject $subject -EKU "Code Signing" -KeySpec "Signature" -KeyUsage "DigitalSignature" -FriendlyName $name -Path $pfxPath -Password $emptyPass
        Export-Certificate -Cert $cert -FilePath $cerPath
        if (! $?)
        {
            Write-Host "[!] Failed to create self signing certificate!"
        }
    }
    else
    {
        Write-Host "[!] Failed to verify '$file'!"
        Exit 1
    }
}
```

**Comment by marmarek** [comment]
I'm not sure how I've done this, but I've got WDK path in `HKLM\Software\Wow6432Node\Microsoft\Windows Kits\Installed Roots`. It's WDK 8.1, on Windows 7. And `get-be.ps1` can't find it. Nothing during installation suggested it is 32bit only or such.
Should this case be handled by `get-be.ps1` too, or something gone terribly wrong?

Anyway, previous issues seems to be fixed now.

**Comment by marmarek** [comment]
I've installed WDK 10, and it works.
Then, when I start the build (`make qubes`) I hit the same TLS issue in `prepare-be.ps1` (on downloading 7zip). But fixing this technically would be an improvement separate from this PR.

**Review by marmarek — APPROVED** [review]

**Comment by historicbruno** [comment]
> I'm not sure how I've done this, but I've got WDK path in `HKLM\Software\Wow6432Node\Microsoft\Windows Kits\Installed Roots`. It's WDK 8.1, on Windows 7. And `get-be.ps1` can't find it. Nothing during installation suggested it is 32bit only or such.
> Should this case be handled by `get-be.ps1` too, or something gone terribly wrong?

WoW64 is for 32-bit applications running on 64-bit Windows, which makes sense because the WDKs bundle both 32- and 64-bit binaries. So that should be the registry location for 32-bit apps, without realizing they are running on a 64-bit OS. In fact, I have that same registry keys on my Win 10 build system. We could always check both paths for completeness, it wouldn't add much complexity to the script.

> Then, when I start the build (`make qubes`) I hit the same TLS issue in `prepare-be.ps1` (on downloading 7zip). But fixing this technically would be an improvement separate from this PR.

Hmm that reminds how much I don't like all the duplication between those two scripts :/

**Comment by marmarek** [comment]
> So that should be the registry location for 32-bit apps, without realizing they are running on a 64-bit OS. In fact, I have that same registry keys on my Win 10 build system.

The problem is I had "Windows Kits" entry only there, not in `HKLM\Software\Microsoft`. But I think something was wrong with that installation, as I couldn't find `makecert.exe` there. Lets leave is as is.

> Hmm that reminds how much I don't like all the duplication between those two scripts :/

The idea is for `get-be.ps1` to be self contained, so it can be used to populate qubes-builder by downloading just one file. So, parts of `prepare-be.ps1` were copied... If you'd like to reduce the  duplication, while keeping `get-be.ps1` self contained, it would be great.

**Comment by historicbruno** [comment]
Should I commit a fix for the `prepare-be.ps1` TLS issue, or wait since these changes are already approved?

I'm not quite used to these proper Github PRs :)

**Comment by marmarek** [comment]
> Should I commit a fix for the `prepare-be.ps1` TLS issue, or wait since these changes are already approved?

Better in new PR.

**Pull request merged**
